#!/usr/bin/env node
/* places.mjs — the GeoGuesser photo pool: real places, at least a thousand.

   Every place is a Natural Earth populated place (public domain), in one of
   the 195 quizzed countries, and is kept only if it lies inside its own
   country's shape on the app's map (map.js nearCountry) — a place the map
   puts in the wrong country is exactly what a child would notice.

   Spread, not density: each country gets a quota that grows with the square
   root of how many places Natural Earth lists for it (3 to 32), biggest
   towns first, and no two places within 20 km. So India, Brazil and the US
   are well covered without drowning out Kenya or Laos.

   Output: app/src/data/places.js. Whether Google has Street View imagery at
   a place is NOT decided here — tools/geo/verify-streetview.mjs asks
   Google's free metadata endpoint, once a key exists, and writes
   app/src/data/sv-ok.js. Until then the game still works: a place with no
   imagery answers 404 and is skipped, never counted.

     NE=… node places.mjs */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..');
const NE = process.env.NE || path.join(HERE, 'ne');
const { QUIZ, byCc, haversine } = await import(path.join(ROOT, 'app/src/geo.js'));
const { nearCountry } = await import(path.join(ROOT, 'app/src/map.js'));

const places = JSON.parse(fs.readFileSync(path.join(NE, 'ne_10m_populated_places_simple.geojson'))).features.map((f) => f.properties);
const per = {};
for (const p of places) if (byCc[p.iso_a2] && byCc[p.iso_a2].quiz) (per[p.iso_a2] = per[p.iso_a2] || []).push(p);

const out = [];
const slug = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
let dropped = 0;
for (const c of QUIZ) {
  const list = (per[c.cc] || []).slice().sort((a, b) => (b.pop_max || 0) - (a.pop_max || 0));
  const quota = Math.max(3, Math.min(32, Math.round(Math.sqrt(list.length) * 3.4)));
  const mine = [];
  for (const p of list) {
    if (mine.length >= quota) break;
    const at = [+p.latitude.toFixed(4), +p.longitude.toFixed(4)];
    if (mine.some((m) => haversine(m.at, at) < 20)) continue;
    if (!nearCountry(at, c.cc)) { dropped++; continue; }
    mine.push({ id: `${c.cc.toLowerCase()}-${slug(p.nameascii || p.name)}`, n: p.name, cc: c.cc, at, big: (p.pop_max || 0) >= 1e6 ? 1 : 0 });
  }
  out.push(...mine);
}
/* ids must be unique */
const seen = new Map();
for (const p of out) { const k = seen.get(p.id) || 0; seen.set(p.id, k + 1); if (k) p.id += '-' + (k + 1); }

if (out.length < 1000) { console.error(`only ${out.length} places — the game promises at least 1,000`); process.exit(1); }
const countries = new Set(out.map((p) => p.cc)).size;
fs.writeFileSync(path.join(ROOT, 'app/src/data/places.js'),
  `/* places.js — GENERATED by tools/geo/places.mjs from Natural Earth populated places. Do not edit. */\n` +
  `export const PLACES = ${JSON.stringify(out)};\n`);
console.log(`places: ${out.length} in ${countries} countries (${dropped} dropped as outside their country on the map)`);
