/* The Restless Earth — inside the Earth, moving plates, volcanoes and
   earthquakes, rocks, and the supercontinent. Ages 11–14. */
import { mc, bank } from './kit.js';
import { layers, boundary } from '../figs.js';

export const WORLD = { id: 'restless', name: 'The Restless Earth', short: 'Restless Earth', glyph: '🌋', band: '11-14', ink: '#A33A1C', tint: '#FBE6DE',
  blurb: 'The layers inside the Earth, the plates that carry the continents, volcanoes and earthquakes, the rock cycle, and Pangaea.' };

const USGS = 'US Geological Survey — “This Dynamic Earth”';

export const STOPS = [
  { id: 'earth-layers', title: 'Inside the Earth', glyph: '🥚', band: '11-14',
    hook: 'If the Earth were an egg, the crust we live on would be thinner than its shell.',
    idea: [`<span class="fig-c">${layers()}</span>`, 'The <b>crust</b> is the thin rocky outside. Below it is the <b>mantle</b>: hot rock that flows very slowly.', 'At the centre is the <b>core</b>, mostly iron and nickel. The <b>outer core</b> is liquid; the <b>inner core</b> is solid, squeezed by the weight above it.', 'The moving liquid iron of the outer core makes Earth’s magnetic field — what a compass needle feels.'],
    why: 'The slow flow of the mantle is what moves the continents.',
    src: [USGS, 'Encyclopaedia Britannica — “Earth: the interior”'],
    gen: bank([
      { lv: 1, q: 'Which layer of the Earth do we live on?', a: 'the crust', w: ['the mantle', 'the outer core', 'the inner core'], html: layers },
      { lv: 1, q: 'What is at the very centre of the Earth?', a: 'the inner core', w: ['the crust', 'the mantle', 'the ocean'] },
      { lv: 2, q: 'Which part of the core is liquid?', a: 'the outer core', w: ['the inner core', 'the crust', 'none of it'] },
      { lv: 2, q: 'The core is made mostly of…', a: 'iron and nickel', w: ['water and ice', 'sand and clay', 'gold and silver'] },
      { lv: 2, q: 'The thickest layer of the Earth is…', a: 'the mantle', w: ['the crust', 'the inner core', 'the atmosphere'] },
      { lv: 3, q: 'Why is the inner core solid even though it is hotter than the outer core?', a: 'the pressure there is enormous', w: ['it is made of ice', 'it is cooler than the surface', 'the Sun freezes it'] },
      { lv: 3, q: 'What makes Earth’s magnetic field?', a: 'liquid iron moving in the outer core', w: ['the Moon', 'magnets in the crust', 'the oceans'] },
      { lv: 1, q: 'Which layer lies just under the crust?', a: 'the mantle', w: ['the inner core', 'the outer core', 'the sky'] },
      { lv: 1, q: 'As you go deeper into the Earth, it gets…', a: 'hotter', w: ['colder', 'the same temperature', 'full of air'] },
      { lv: 1, q: 'If the Earth were an egg, the crust would be its…', a: 'shell', w: ['yolk', 'white', 'whole inside'] },
      { lv: 1, q: 'A compass needle points north because it feels…', a: 'Earth’s magnetic field', w: ['the wind', 'the Sun’s heat', 'the Moon’s pull'] },
      { lv: 1, q: 'What is the crust made of?', a: 'rock', w: ['liquid iron', 'ice', 'air'] },
      { lv: 1, tf: true, q: 'The rock of the mantle is hot and flows very, very slowly.' },
      { lv: 1, tf: true, q: 'Even the deepest mines are still in the crust.' },
      { lv: 1, tf: false, q: 'The centre of the Earth is hollow.' },
      { lv: 1, tf: false, q: 'The crust is the same thickness everywhere.' },
      { lv: 2, q: 'Where is the crust thinnest?', a: 'under the oceans', w: ['under tall mountains', 'under the middle of continents', 'under deserts'] },
      { lv: 2, q: 'What slowly moves the continents?', a: 'the flow of the mantle', w: ['the wind', 'ocean tides', 'the Moon'] },
      { lv: 3, q: 'The crust and the top of the mantle together form the…', a: 'lithosphere', w: ['atmosphere', 'hydrosphere', 'biosphere'] },
      { lv: 3, q: 'How do scientists know what is inside the Earth?', a: 'by studying earthquake waves that pass through it', w: ['by digging to the centre', 'by sending a robot down', 'by guessing'] },
    ]) },
  { id: 'plates', title: 'Moving plates', glyph: '🧩', band: '11-14',
    hook: 'The Atlantic Ocean gets wider every year — about as fast as your fingernails grow.',
    idea: ['The crust is broken into huge pieces called <b>tectonic plates</b>. They float on the mantle and move a few centimetres a year.', `Where plates <b>pull apart</b> (divergent), new crust forms — like the Mid-Atlantic Ridge.<span class="fig-row">${boundary('divergent')}</span>`, `Where they <b>push together</b> (convergent), mountains rise or one plate sinks under another — the Himalaya formed where India pushed into Asia.<span class="fig-row">${boundary('convergent')}</span>`, `Where they <b>slide past</b> (transform), the ground shakes — like the San Andreas Fault in California.<span class="fig-row">${boundary('transform')}</span>`],
    why: 'Plates explain earthquakes, volcanoes, mountains and ocean trenches — with one idea.',
    src: [USGS],
    gen: bank([
      { lv: 1, q: 'The huge pieces the Earth’s crust is broken into are called…', a: 'tectonic plates', w: ['continents', 'hemispheres', 'layers'] },
      { lv: 1, q: 'About how fast do plates move?', a: 'a few centimetres a year', w: ['a few kilometres a day', 'they never move', 'a metre every minute'] },
      { lv: 2, q: 'Plates pulling apart make a…', a: 'divergent boundary', w: ['convergent boundary', 'transform boundary', 'tropic'], html: () => boundary('divergent') },
      { lv: 2, q: 'Plates pushing together make a…', a: 'convergent boundary', w: ['divergent boundary', 'transform boundary', 'meridian'], html: () => boundary('convergent') },
      { lv: 2, q: 'Plates sliding past each other make a…', a: 'transform boundary', w: ['divergent boundary', 'convergent boundary', 'delta'], html: () => boundary('transform') },
      { lv: 3, q: 'The Himalaya was made when India’s plate…', a: 'pushed into Asia', w: ['pulled away from Africa', 'sank into the ocean', 'slid past Australia'] },
      { lv: 3, q: 'The Mid-Atlantic Ridge is where plates are…', a: 'pulling apart', w: ['pushing together', 'sliding past', 'not moving'] },
      { lv: 3, q: 'The San Andreas Fault in California is a…', a: 'transform boundary', w: ['divergent boundary', 'convergent boundary', 'volcano'] },
      { lv: 1, q: 'What do the plates float on?', a: 'the mantle', w: ['the ocean', 'the air', 'the inner core'] },
      { lv: 1, q: 'When two plates push together, the land can be pushed up into…', a: 'mountains', w: ['rivers', 'deserts', 'lakes'] },
      { lv: 1, q: 'Rocks suddenly slipping where plates meet cause…', a: 'earthquakes', w: ['rainbows', 'tides', 'snow'] },
      { lv: 1, q: 'A crack in the rock where the two sides move is called a…', a: 'fault', w: ['ridge', 'delta', 'valley'] },
      { lv: 1, q: 'The line where two plates meet is called a plate…', a: 'boundary', w: ['centre', 'core', 'pole'] },
      { lv: 1, tf: true, q: 'Tectonic plates carry the continents on them.' },
      { lv: 1, tf: true, q: 'The Atlantic Ocean is slowly getting wider.' },
      { lv: 1, tf: false, q: 'The whole crust is one single plate.' },
      { lv: 1, tf: false, q: 'Plates move only under the oceans, never under land.' },
      { lv: 2, q: 'When plates pull apart under the sea, what forms in the gap?', a: 'new ocean crust', w: ['a desert', 'a glacier', 'a coral reef'] },
      { lv: 3, q: 'One plate sinking under another is called…', a: 'subduction', w: ['erosion', 'evaporation', 'weathering'] },
    ]) },
  { id: 'volcanoes-quakes', title: 'Volcanoes and earthquakes', glyph: '🌋', band: '11-14',
    hook: 'Around the edge of the Pacific is a ring where most of the world’s earthquakes and volcanoes happen.',
    idea: ['Melted rock underground is <b>magma</b>. When it comes out of a volcano it is called <b>lava</b>.', 'An <b>earthquake</b> is the ground shaking when rocks along a fault suddenly slip. Its strength is its <b>magnitude</b>.', 'An earthquake under the sea can push up a huge wave: a <b>tsunami</b>.', 'The <b>Ring of Fire</b> around the Pacific Ocean is where plates meet — Japan, Indonesia, the Andes and the west coast of the Americas are on it.'],
    why: 'Knowing where the plates meet tells people where to build carefully.',
    src: [USGS, 'US Geological Survey — “Ring of Fire”'],
    gen: bank([
      { lv: 1, q: 'Melted rock that comes out of a volcano is called…', a: 'lava', w: ['magma', 'basalt', 'ash'] },
      { lv: 1, q: 'Melted rock still under the ground is called…', a: 'magma', w: ['lava', 'granite', 'mud'] },
      { lv: 2, q: 'A giant sea wave caused by an earthquake under the sea is a…', a: 'tsunami', w: ['monsoon', 'hurricane', 'tide'] },
      { lv: 2, q: 'The ring of volcanoes and earthquakes around the Pacific is called…', a: 'the Ring of Fire', w: ['the Tropic of Cancer', 'the Equator', 'the Mid-Atlantic Ridge'] },
      { lv: 2, q: 'Which of these countries is on the Ring of Fire?', a: 'Japan', w: ['Egypt', 'Poland', 'Mongolia'] },
      { lv: 3, q: 'Most earthquakes happen…', a: 'where plates meet', w: ['in the middle of plates', 'only at the poles', 'only under deserts'] },
      { lv: 3, q: 'The strength of an earthquake is called its…', a: 'magnitude', w: ['latitude', 'altitude', 'longitude'] },
      { lv: 1, q: 'The opening at the top of a volcano is its…', a: 'crater', w: ['trench', 'delta', 'ridge'] },
      { lv: 1, q: 'Lava, ash and gas bursting out of a volcano is called an…', a: 'eruption', w: ['avalanche', 'eclipse', 'erosion'] },
      { lv: 1, q: 'When lava cools and hardens, it becomes…', a: 'new rock', w: ['sand', 'ice', 'soil'] },
      { lv: 1, q: 'What is a seismometer used for?', a: 'measuring earthquakes', w: ['measuring rain', 'measuring wind', 'measuring temperature'] },
      { lv: 1, q: 'Indoors, when the ground starts to shake, you should…', a: 'drop, take cover under a strong table and hold on', w: ['stand next to a window', 'take the lift', 'run down the stairs'] },
      { lv: 1, q: 'You are by the sea and the ground shakes hard. What should you do?', a: 'go to high ground', w: ['go down to the beach', 'stay on the sand', 'go for a swim'] },
      { lv: 1, tf: true, q: 'Volcanoes can form under the sea.' },
      { lv: 1, tf: true, q: 'Most earthquakes are too small for people to feel.' },
      { lv: 1, tf: false, q: 'Scientists can tell the exact day an earthquake will happen.' },
      { lv: 1, tf: false, q: 'Earthquakes only happen in hot countries.' },
      { lv: 2, q: 'A volcano that is quiet now but may erupt again is…', a: 'dormant', w: ['extinct', 'frozen', 'melted'] },
      { lv: 2, tf: true, q: 'The place on the surface right above where an earthquake starts is called the epicentre.' },
      { lv: 3, q: 'The smaller shakes that follow a big earthquake are called…', a: 'aftershocks', w: ['tides', 'tsunamis', 'eruptions'] },
      { lv: 3, q: 'Volcanoes in the middle of a plate, like Hawaii’s, sit over a…', a: 'hotspot', w: ['trench', 'fault', 'glacier'] },
    ]) },
  { id: 'rocks', title: 'The rock cycle', glyph: '🪨', band: '11-14',
    hook: 'The marble of the Taj Mahal was once limestone — changed by heat and pressure deep underground.',
    idea: ['<b>Igneous</b> rock forms when magma or lava cools: granite, basalt.', '<b>Sedimentary</b> rock forms from layers of sand, mud or shells pressed together: sandstone, limestone. Fossils are found here.', '<b>Metamorphic</b> rock is rock changed by heat and pressure: limestone becomes marble, mudstone becomes slate.', 'Over millions of years every rock can become every other kind — the <b>rock cycle</b>.'],
    why: 'Rocks are the record of Earth’s history, written in layers.',
    src: ['US Geological Survey — “Rock types”', 'Encyclopaedia Britannica — “Rock cycle”'],
    gen: bank([
      { lv: 1, q: 'Rock made when lava cools is…', a: 'igneous', w: ['sedimentary', 'metamorphic'] },
      { lv: 1, q: 'Rock made from layers of sand pressed together is…', a: 'sedimentary', w: ['igneous', 'metamorphic'] },
      { lv: 1, q: 'Rock changed by heat and pressure is…', a: 'metamorphic', w: ['igneous', 'sedimentary'] },
      { lv: 2, q: 'Marble is made from…', a: 'limestone', w: ['granite', 'basalt', 'coal'] },
      { lv: 2, q: 'In which kind of rock are fossils usually found?', a: 'sedimentary', w: ['igneous', 'metamorphic'] },
      { lv: 2, q: 'Granite is…', a: 'igneous', w: ['sedimentary', 'metamorphic'] },
      { lv: 3, q: 'Slate is made from…', a: 'mudstone or shale', w: ['granite', 'sandstone', 'marble'] },
      { lv: 3, q: 'Basalt forms from…', a: 'lava cooling quickly', w: ['shells pressed together', 'sand in a river', 'marble melting'] },
      { lv: 1, q: 'Rain, wind and ice slowly breaking rock into small pieces is called…', a: 'weathering', w: ['erupting', 'melting', 'freezing'] },
      { lv: 1, q: 'Rivers and wind carrying bits of rock away is called…', a: 'erosion', w: ['evaporation', 'eruption', 'condensation'] },
      { lv: 1, q: 'Tiny bits of rock, sand and mud carried by water are called…', a: 'sediment', w: ['magma', 'lava', 'crystals'] },
      { lv: 1, q: 'Rocks are made of tiny grains called…', a: 'minerals', w: ['cells', 'seeds', 'bubbles'] },
      { lv: 1, q: 'How long does the rock cycle take?', a: 'millions of years', w: ['a few days', 'one year', 'a few minutes'] },
      { lv: 1, tf: true, q: 'A fossil is the remains or trace of a living thing kept in rock.' },
      { lv: 1, tf: false, q: 'Rocks never change.' },
      { lv: 1, tf: false, q: 'All the rocks on Earth are the same age.' },
      { lv: 2, q: 'Limestone is…', a: 'sedimentary', w: ['igneous', 'metamorphic'] },
      { lv: 2, q: 'Coal formed from…', a: 'plants buried long ago', w: ['melted iron', 'sea salt', 'cooled lava'] },
      { lv: 2, tf: true, q: 'In a stack of sedimentary rock, the lower layers are usually older than the layers on top.' },
      { lv: 3, q: 'Pumice can float on water because it is…', a: 'full of gas bubbles', w: ['made of wood', 'very cold', 'covered in oil'] },
      { lv: 3, q: 'Granite has big crystals because it cooled…', a: 'slowly, deep underground', w: ['quickly in the air', 'quickly in the sea', 'in a forest fire'] },
    ]) },
  { id: 'pangaea', title: 'When the continents were one', glyph: '🧭', band: '11-14',
    hook: 'Look at the coasts of South America and Africa. They fit together like puzzle pieces.',
    idea: ['About 300 million years ago almost all the land was joined in one supercontinent, <b>Pangaea</b>.', 'Alfred <b>Wegener</b> proposed in 1912 that continents drift. His clues: coasts that fit, the same fossils on continents now oceans apart, and matching rocks.', 'Few believed him until the 1960s, when maps of the sea floor showed it spreading. Now it is the theory of <b>plate tectonics</b>.', 'Walk the whole story in the Library: <b>Earth Through Time</b>.'],
    why: 'It is one of the great “how do we know?” stories in science — a good idea that waited fifty years for its evidence.',
    src: [USGS, 'Encyclopaedia Britannica — “Alfred Wegener”'],
    gen: bank([
      { lv: 1, q: 'The supercontinent that joined almost all the land was called…', a: 'Pangaea', w: ['Atlantis', 'Eurasia', 'Oceania'] },
      { lv: 2, q: 'Who proposed that the continents drift?', a: 'Alfred Wegener', w: ['Gerardus Mercator', 'Charles Darwin', 'Isaac Newton'] },
      { lv: 2, q: 'Which two continents’ coasts fit together best?', a: 'South America and Africa', w: ['Europe and Australia', 'Asia and Antarctica', 'North America and India'] },
      { lv: 2, tf: true, q: 'The same kinds of fossils are found on continents that are now oceans apart.' },
      { lv: 3, q: 'What finally convinced scientists that continents move?', a: 'evidence that the sea floor is spreading', w: ['a photo from space', 'a vote', 'finding Pangaea on an old map'] },
      { lv: 3, q: 'About when was Pangaea joined together?', a: 'about 300 million years ago', w: ['about 3,000 years ago', 'about 30 years ago', 'about 3 billion years ago'] },
      { lv: 1, q: 'One enormous landmass made of almost all the continents is called a…', a: 'supercontinent', w: ['peninsula', 'island chain', 'hemisphere'] },
      { lv: 1, q: 'Pangaea slowly broke apart into…', a: 'the continents we know today', w: ['the planets', 'the oceans', 'islands of ice'] },
      { lv: 1, q: 'Wegener’s idea that the continents move is called…', a: 'continental drift', w: ['the water cycle', 'the Big Bang', 'global warming'] },
      { lv: 1, q: 'Scientists who study rocks and how the Earth changes are called…', a: 'geologists', w: ['astronomers', 'biologists', 'historians'] },
      { lv: 1, q: 'Today, Africa and South America are separated by…', a: 'the Atlantic Ocean', w: ['the Pacific Ocean', 'the Indian Ocean', 'the Arctic Ocean'] },
      { lv: 1, tf: true, q: 'The continents are still moving today.' },
      { lv: 1, tf: true, q: 'Long ago, India was not joined to Asia.' },
      { lv: 1, tf: false, q: 'Everyone believed Wegener’s idea straight away.' },
      { lv: 1, tf: false, q: 'Pangaea broke apart in just a few years.' },
      { lv: 2, q: 'The name Pangaea comes from Greek words meaning…', a: 'all lands', w: ['big sea', 'old world', 'hot rock'] },
      { lv: 2, tf: true, q: 'Early dinosaurs lived when the land was joined as Pangaea.' },
      { lv: 2, tf: false, q: 'Pangaea was the first land there ever was on Earth.' },
      { lv: 3, q: 'The one giant ocean around Pangaea is called…', a: 'Panthalassa', w: ['the Atlantic', 'the Arctic', 'the Mediterranean'] },
      { lv: 3, q: 'Fossils of the small reptile Mesosaurus are found in South America and in…', a: 'southern Africa', w: ['Greenland', 'Japan', 'Iceland'] },
      { lv: 3, q: 'Scratches left by ancient glaciers in India, Africa and Australia show these lands were once…', a: 'joined, near the South Pole', w: ['under the sea', 'part of the Moon', 'near the North Pole'] },
    ]) },
];
